### ISSUE TITLE
Implement a layers view

### ISSUE THREAD

**Issue by zeyadhazem** [DDMAL/Pixel.js#15]
The layers view will showcase a preview of the content of all layers that a user has modified in the current project.

**Comment by PotassiumK** [comment]
While canvas doesn't allow layering per se, we can implement several canvases one on top of another which gives the impression of layers.

**Comment by fujinaga** [comment]
One way to do layers is to assign a 32-bit integer to each pixel; then turn each bit on if it belongs to one of 32 layers. I don't expect we'd have more than 32 layers.

**Comment by zeyadhazem** [comment]
Yes definitely that was one solution that we were discussing as well

**Comment by ahankinson** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas
https://www.html5rocks.com/en/tutorials/canvas/performance/

I'm not sure if the 32-bit integer trick will work. As I understand it each pixel on the canvas is a quad of four integers `[r, g, b, a]`, each accepting an 8-bit value (0-255), so every image in the canvas is necessarily a 24-bit RGBA image. This is implemented as a one-dimensional vector.

As I understand it, though, you really only need one canvas, and then an array of equivalent size containing the label for a given pixel. So if you have a 100 x 100 image, you will have an array of length 10,000. You then just need to store in a `label` array an integer corresponding to the label for that pixel: 0 = background, 1 = staff, 2 = text, n = ??. 

When the user hovers over a given pixel, then, you can do a very quick lookup to get that label from your label array, since image[idx] = label[idx]. You can also colour a given pixel according to its label:

pseudocode: 

```
for int p in imageArr:
     label = labelArr[p]
     image[p] = [r(label), g(label), b(label), 255]
```

where `r, g, b` values can be computed according to the value of the label.

**Comment by fujinaga** [comment]
My 32-bit integer "trick" is essentially the same as your "label" array. My suggestion was to use each array element as a bit mask, to indicate whether a pixel belong to a certain layer. The advantage is that a pixel can belong to multiple layers.

**Comment by ahankinson** [comment]
Ah, ok. It wasn't clear whether you wanted to assign the integer within the canvas data array itself, or outside.

**Comment by zeyadhazem** [comment]
Multiple optimization tricks in this issue, won't close until implemented
